// 给action注册事件处理函数。当这个函数被触发时候，将状态提交到mutations中处理
// ES6精简写法
export const modifyTitle = ({commit}, val) => commit('modifyTitle', val)
export const modifyTypeDjbh = ({commit}, val) => commit('modifyTypeDjbh', val)
export const modifyDjbh = ({commit}, val) => commit('modifyDjbh', val)
export const modifyDjbhItem = ({commit}, val) => commit('modifyDjbhItem', val)
export const modifyMissionTaskType = ({commit}, val) => commit('modifyMissionTaskType', val)
export const modifyMissionFlowId = ({commit}, val) => commit('modifyMissionFlowId', val)
export const modifyMissionRows = ({commit}, val) => commit('modifyMissionRows', val)
export const modifyMissionEmpNum = ({commit}, val) => commit('modifyMissionEmpNum', val)
export const modifyMissionFlowDetail = ({commit}, val) => commit('modifyMissionFlowDetail', val)
export const modifyPathStatus = ({commit}, val) => commit('modifyPathStatus', val)
export const modifyFlowData = ({commit}, val) => commit('modifyFlowData', val)
export const modifyMissionTitle = ({commit}, val) => commit('modifyMissionTitle', val)
export const modifyDepart = ({commit}, val) => commit('modifyDepart', val)
export const modifyCompany = ({commit}, val) => commit('modifyCompany', val)
export const modifyChartTitle = ({commit}, val) => commit('modifyChartTitle', val)
