// 获取最终的状态信息
export const title = state => state.title
export const typeDjbh = state => state.typeDjbh
export const djbh = state => state.djbh
export const djbhItem = state => state.djbhItem
export const missionTaskType = state => state.missionTaskType
export const missionFlowId = state => state.missionFlowId
export const missionRows = state => state.missionRows
export const missionEmpNum = state => state.missionEmpNum
export const missionFlowDetail = state => state.missionFlowDetail
export const pathStatus = state => state.pathStatus
export const flowData = state => state.flowData
export const missionTitle = state => state.missionTitle
export const depart = state => state.depart
export const company = state => state.company
export const chartTitle = state => state.chartTitle
export const allCompanys = state => state.allCompanys
export const allDeparts = state => state.allDeparts
export const chartType = state => state.chartType
export const chartTypeKey = state => state.chartTypeKey
export const time = state => state.time
export const companyId = state => state.companyId
